auth            required        pam_faillock.so preauth
auth            sufficient      pam_fprintd.so
auth            sufficient      pam_unix.so try_first_pass likeauth nullok
auth            [default=die]   pam_faillock.so authfail
